title: Dr. Tanja Blascheck
email: research@blascheck.eu
description: "Academic & Professional CV site"
baseurl: "" # Leave empty if using username.github.io, or "/repo-name" if hosted on a subpath
url: "https://https://tanjablascheck.github.io/"

theme: minima # Default Jekyll theme (or leave unset if custom layout)
markdown: kramdown